### ISSUE TITLE
update citation in globi.json

### ISSUE THREAD

**Issue by jhpoelen** [fgabriel1891/Plant-Frugivore-Interactions-SouthEastAsia#1]
Hi!

I noticed that you added your frugivore data. You can now find it through GloBI (see https://www.globalbioticinteractions.org/?accordingTo=globi%3Afgabriel1891%2FPlant-Frugivore-Interactions-SouthEastAsia&interactionType=interactsWith).

Suggest to update citation string in globi.json with the citation to your datasets. Right now is it set to the default template dataset citation.

Hope this helps, 
-jorrit

**Comment by fgabriel1891** [comment]
Hi Jorrit,  Citation is updated now. Thanks for the heads-up.
