### ISSUE TITLE
invalid DOI "hdl.handle.net/2292/605"

### ISSUE THREAD

**Issue by jhpoelen** [fgabriel1891/Plant-Frugivore-Interactions-SouthEastAsia#7]
Hi @fgabriel1891 ! 
I was just going over some log files, and noticed that your interactions.tsv contains a value "hdl.handle.net/2292/605" in column "referenceDoi". Suggest to move the value to a new column "referenceUrl" using "http://hdl.handle.net/2292/605" . The value "hdl.handle.net/2292/605" is not a valid DOI.
Hope this helps!

**Comment by fgabriel1891** [comment]
@jhpoelen It's done! Thanks for noticing it
